# Generated by Django 4.0.1 on 2022-05-30 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('edad', models.FloatField(max_length=3)),
                ('dni', models.CharField(max_length=20)),
                ('fecha_cumpleaños', models.CharField(max_length=20)),
            ],
        ),
    ]
